services:
  backend:
    image: prajwalg06/devops-backend:latest
    ports:
      - "8000:8000"

  frontend:
    image: prajwalg06/devops-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend